/* tslint:disable */
/* eslint-disable */
/**
 * Public Service Docs
 * Public Service endpoints...
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ClimateResilienceForecastInfo
 */
export interface ClimateResilienceForecastInfo {
    /**
     * Name of the location.
     * @type {string}
     * @memberof ClimateResilienceForecastInfo
     */
    'name': string;
    /**
     * Region of the location.
     * @type {string}
     * @memberof ClimateResilienceForecastInfo
     */
    'region': string;
    /**
     * Country of the location.
     * @type {string}
     * @memberof ClimateResilienceForecastInfo
     */
    'country': string;
    /**
     * Latitude of the location.
     * @type {number}
     * @memberof ClimateResilienceForecastInfo
     */
    'lat': number;
    /**
     * Longitude of the location.
     * @type {number}
     * @memberof ClimateResilienceForecastInfo
     */
    'lon': number;
    /**
     * Temperature in Celsius.
     * @type {number}
     * @memberof ClimateResilienceForecastInfo
     */
    'temp_c': number;
    /**
     * Temperature in Fahrenheit.
     * @type {number}
     * @memberof ClimateResilienceForecastInfo
     */
    'temp_f': number;
    /**
     * Whether it is day or night.
     * @type {number}
     * @memberof ClimateResilienceForecastInfo
     */
    'is_day': number;
    /**
     * Condition of the location.
     * @type {string}
     * @memberof ClimateResilienceForecastInfo
     */
    'condition': string;
    /**
     * Condition icon of the location.
     * @type {string}
     * @memberof ClimateResilienceForecastInfo
     */
    'condition_icon': string;
    /**
     * Condition code of the location.
     * @type {number}
     * @memberof ClimateResilienceForecastInfo
     */
    'condition_code': number;
    /**
     * Wind speed in kilometers per hour.
     * @type {number}
     * @memberof ClimateResilienceForecastInfo
     */
    'wind_kph': number;
}

/**
 * WeatherApi - axios parameter creator
 * @export
 */
export const WeatherApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weatherControllerFetchClimateResilienceForecast: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/public/weather/climate-resilience-forecast`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WeatherApi - functional programming interface
 * @export
 */
export const WeatherApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WeatherApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async weatherControllerFetchClimateResilienceForecast(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ClimateResilienceForecastInfo>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.weatherControllerFetchClimateResilienceForecast(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeatherApi.weatherControllerFetchClimateResilienceForecast']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WeatherApi - factory interface
 * @export
 */
export const WeatherApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WeatherApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weatherControllerFetchClimateResilienceForecast(options?: RawAxiosRequestConfig): AxiosPromise<Array<ClimateResilienceForecastInfo>> {
            return localVarFp.weatherControllerFetchClimateResilienceForecast(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WeatherApi - object-oriented interface
 * @export
 * @class WeatherApi
 * @extends {BaseAPI}
 */
export class WeatherApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherApi
     */
    public weatherControllerFetchClimateResilienceForecast(options?: RawAxiosRequestConfig) {
        return WeatherApiFp(this.configuration).weatherControllerFetchClimateResilienceForecast(options).then((request) => request(this.axios, this.basePath));
    }
}



